kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  annotations:
    kubesailEditorUid: fa3a4477-d25d-4483-a137-0d544be3d21e
    kubesail.com/template: erulabs/nextcloud:v26
apiVersion: apps/v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:24.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: NEXTCLOUD_ADMIN_USER
              value: "{{ NEXTCLOUD_ADMIN_USER|admin }}"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "{{ NEXTCLOUD_ADMIN_PASSWORD|RANDOM()|NextCloud Superuser password }}"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.{{ CLUSTER_ADDRESS }}
            - name: OVERWRITEPROTOCOL
              value: https
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8
          volumeMounts:
            - name: nextcloud-files
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-files
          persistentVolumeClaim:
            claimName: nextcloud-files

---
kind: Ingress
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    kubesailEditorUid: 30e719db-e91b-4f67-95eb-3bbb7a0c8f16
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    kubesail.com/template: erulabs/nextcloud:v26
apiVersion: networking.k8s.io/v1
spec:
  tls:
    - hosts:
        - nextcloud.{{ CLUSTER_ADDRESS }}
  rules:
    - host: nextcloud.{{ CLUSTER_ADDRESS }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nextcloud
                port:
                  name: http

---
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-files
  annotations:
    kubesailEditorUid: 590590f3-99d9-49ce-bec1-0048334e0404
    kubesail.com/template: erulabs/nextcloud:v26
apiVersion: v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 050Gi

---
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  annotations:
    kubesailEditorUid: 9b3f4c93-870c-413e-b1e7-998761d005b3
    kubesail.com/template: erulabs/nextcloud:v26
apiVersion: v1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: nextcloud
